In [2]:
import numpy as np
from scipy.signal import wiener
import cv2 as cv
import import_ipynb
import ImageDenoise as ID


importing Jupyter notebook from ImageDenoise.ipynb


In [10]:
img=cv.imread("/home/boss/Documents/Dataset_BUSI_with_GT/malignant/malignant (2).png",1)

# blur = cv.bilateralFilter(img,9,75,75)
nimg = cv.ximgproc.anisotropicDiffusion(img, alpha=0.1, K=0.02, niters=20)

filterimg=ID.contrast_enhanceWMedian(nimg)

segment=ID.fuzzycMeans(filterimg,3)
cv.imshow("org",img)
cv.imshow("filter",filterimg)
cv.imshow('filtered img',segment)
cv.waitKey(0)
cv.destroyAllWindows()

QObject::moveToThread: Current thread (0x3b0d5e0) is not the object's thread (0x2827600).
Cannot move to target thread (0x3b0d5e0)

QObject::moveToThread: Current thread (0x3b0d5e0) is not the object's thread (0x2827600).
Cannot move to target thread (0x3b0d5e0)

QObject::moveToThread: Current thread (0x3b0d5e0) is not the object's thread (0x2827600).
Cannot move to target thread (0x3b0d5e0)

QObject::moveToThread: Current thread (0x3b0d5e0) is not the object's thread (0x2827600).
Cannot move to target thread (0x3b0d5e0)

QObject::moveToThread: Current thread (0x3b0d5e0) is not the object's thread (0x2827600).
Cannot move to target thread (0x3b0d5e0)

QObject::moveToThread: Current thread (0x3b0d5e0) is not the object's thread (0x2827600).
Cannot move to target thread (0x3b0d5e0)

QObject::moveToThread: Current thread (0x3b0d5e0) is not the object's thread (0x2827600).
Cannot move to target thread (0x3b0d5e0)

QObject::moveToThread: Current thread (0x3b0d5e0) is not the object's thread

In [13]:
img=cv.imread("/home/boss/Documents/Dataset_BUSI_with_GT/malignant/malignant (1).png",1)
# img=cv.imread("/home/boss/Downloads/frame extract/dataset/ankitframe0.jpg")
# smoothimg=wiener(img,mysize=5)
# nimg=np.array(smoothimg,dtype=np.uint8)
# imggray=cv.cvtColor(segment,cv.COLOR_BGR2GRAY)
# threshval,threshold=cv.threshold(imggray,0,255,cv.THRESH_BINARY+cv.THRESH_OTSU)

imag=ID.noise_remMedianWeiner(img)
val=ID.CLAHEcontrastEnhance(imag)
img1=cv.cvtColor(val,cv.COLOR_RGB2GRAY)
thresval,threshimg=cv.threshold(img1,0,255,cv.THRESH_BINARY+cv.THRESH_OTSU)

threshold1=cv.bitwise_not(threshimg)
kernel=np.ones((3,3),np.uint8)
morphimg=cv.morphologyEx(threshold1,cv.MORPH_OPEN,kernel,iterations=2)
bg2=cv.dilate(morphimg,kernel,iterations=1)
print(img.shape)

(598, 449, 3)


In [14]:
dist_transform = cv.distanceTransform(morphimg,cv.DIST_L2,5)
ret, sure_fg = cv.threshold(dist_transform,0.7*dist_transform.max(),255,0)
sure_fg = np.uint8(sure_fg)

In [15]:
unknown = np.subtract(bg2, sure_fg)
# cv.imshow('unknown', unknown)
# cv.imshow("thres",threshold1)
# cv.waitKey(0)
# cv.destroyAllWindows()

In [19]:
ret, markers = cv.connectedComponents(sure_fg)
print(markers)
markers = markers +1
markers[unknown == 255] = 0
markers = cv.watershed(img, markers)
img[markers == -1] = (255, 0, 0)

cv.imshow("thres",threshold1)
cv.imshow('watershed',img)
cv.waitKey(0)
cv.destroyAllWindows()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


QObject::moveToThread: Current thread (0x5462d40) is not the object's thread (0x568d390).
Cannot move to target thread (0x5462d40)

QObject::moveToThread: Current thread (0x5462d40) is not the object's thread (0x568d390).
Cannot move to target thread (0x5462d40)

QObject::moveToThread: Current thread (0x5462d40) is not the object's thread (0x568d390).
Cannot move to target thread (0x5462d40)

QObject::moveToThread: Current thread (0x5462d40) is not the object's thread (0x568d390).
Cannot move to target thread (0x5462d40)

QObject::moveToThread: Current thread (0x5462d40) is not the object's thread (0x568d390).
Cannot move to target thread (0x5462d40)

QObject::moveToThread: Current thread (0x5462d40) is not the object's thread (0x568d390).
Cannot move to target thread (0x5462d40)

QObject::moveToThread: Current thread (0x5462d40) is not the object's thread (0x568d390).
Cannot move to target thread (0x5462d40)

QObject::moveToThread: Current thread (0x5462d40) is not the object's thread